const extensionToMimeType: Record<string, string> = {
  '7z': 'application/x-7z-compressed',
  'avif': 'image/avif',
  'css': 'text/css',
  'csv': 'text/csv',
  'doc': 'application/msword',
  'docx': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  'eot': 'application/vnd.ms-fontobject',
  'gif': 'image/gif',
  'gz': 'applicaion/gzip',
  'html': 'text/html',
  'ico': 'image/x-icon',
  'jpeg': 'image/jpeg',
  'jpg': 'image/jpeg',
  'js': 'text/javascript',
  'json': 'application/json',
  'mkv': 'video/x-matroska',
  'mp3': 'audio/mpeg',
  'mp4': 'video/mp4',
  'oga': 'audio/ogg',
  'ogg': 'audio/ogg',
  'ogv': 'video/ogg',
  'otf': 'font/otf',
  'pdf': 'application/pdf',
  'png': 'image/png',
  'ppt': 'application/vnd.ms-powerpoint',
  'pptx': 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  'svg': 'image/svg+xml',
  'tar': 'application/x-tar',
  'ttf': 'font/ttf',
  'txt': 'text/plain',
  'wav': 'audio/wav',
  'webm': 'video/webm',
  'webp': 'image/webp',
  'woff': 'font/woff',
  'woff2': 'font/woff2',
  'xls': 'application/vnd.ms-excel',
  'xlsx': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  'zip': 'application/zip',
};

export const getMimeTypeByExtension = (extension: string) =>
  Object.hasOwn(extensionToMimeType, extension) ? extensionToMimeType[extension] : null;
